language: python
python:
  - "3.8.5"
before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - poetry export -f requirements.txt --without-hashes --dev > requirements.txt
  - source $HOME/.poetry/env
install:
  - pip install -r requirements.txt
script:
  - pytest
