language: python
python:
  - "3.8.5"
  - "3.7.8"
  - "3.6.10"
before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry export -f requirements.txt --without-hashes --dev -o requirements.txt
install:
  - pip install -r requirements.txt
  - pip install tox-travis
script:
  - tox
