language: python
python:
  - "3.8.5"
  - "3.7.8"
  - "3.6.10"
before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry export -f requirements.txt --without-hashes --dev -o requirements.txt
install:
  - pip install -r requirements.txt
  - pip install tox-travis
script:
  - tox
  - make -C docs/ html
  - touch docs/_build/html/.nojekyll

before_deploy:
  - poetry config repositories.testpypi https://test.pypi.org/legacy/
  - poetry config http-basic.testpypi $TESTPYPI_USERNAME $TESTPYPI_PASS
  - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASS
  - poetry build

deploy:
  - provider: script
    script:
      - poetry publish -r testpypi
      - poetry publish
    skip_cleanup: true

  - provider: pages:git.
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/_build/html/
    keep_history: true
  on:
    repo: IgnisDa/python-random-markdown-generator
    branch: release
    condition: "$TRAVIS_PYTHON_VERSION == 3.8.5"
